apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-read-delete
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pods-read-delete
subjects:
- kind: ServiceAccount
  name: default 
  namespace: default
roleRef:
  kind: ClusterRole 
  name: pod-read-delete
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-chaos-monkey
spec:
  selector:
    matchLabels:
      app: k8s-chaos-monkey
  template:
    metadata:
      labels:
        app: k8s-chaos-monkey
    spec:
      containers:
      - name: k8s-chaos-monkey
        image: asankov/k8s-chaos-monkey:0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: K8S_CHAOS_NAMESPACE
            value: chaos
          - name: K8S_CHAOS_PERIOD_SECONDS
            value: "10"
